[pytest]
addopts =
    --verbose
    --durations=5
    --cov=nfj
    --cov-report=term-missing
    --html=nfj/tests/coverage_report/report.html
pythonpath = .
testpaths = nfj/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*